### PR TITLE
Light refactoring to node.go

### LINKED ISSUE #65: Refactoring of NodeLookup and FindValue
Both of these functions use basically the exact same code and is as of writing this basically duplications of each other with only minor differences.
Refactor these to minimize duplicate code and make it easier to test

### LINKED ISSUE #74: CLI - Help command not working

### LINKED ISSUE #81: Crashes if a hash of incorrect length is entered in the CLI
# Summary
In the CLI when using GET, if the entered hash is of incorrect length then the program crashes

### PR DESCRIPTION
**Pull request by viktorfrom**
Closes #65 
Closes #81 
Closes #74

### CODE REVIEW

File: internal/kademlia/node.go [hunk 1]
```diff
@@ -140,31 +136,41 @@ func (kademlia *Node) FindValue(hash string) string {
...
+				if *rpc.Payload.Value != "" {
+					return *rpc.Payload.Value
+				}
+
+				// if a node responds with an error remove that node
+				// from the shortlist and from the bucket
+				if err != nil {
+					log.Warn(err)
+					kademlia.RT.RemoveContact(shortList.contacts[i])
+					shortList.contacts = append(shortList.contacts[:i], shortList.contacts[i+1:]...)
```
Comment (97gushan) [inline internal/kademlia/node.go]: after the check on rpc.Payload.Value the method does the same thing as in findNodeAmongContacts, can this be refactored into a different function as well to remove the duplicate code?

File: internal/kademlia/node.go [hunk 2]
```diff
@@ -140,31 +136,41 @@ func (kademlia *Node) FindValue(hash string) string {
...
 					continue
 				} else {
-					rpc, err := kademlia.network.SendFindDataMessage(&shortList.contacts[i], &kademlia.RT.me, hash)
 
 					if rpc.Payload.Value != nil {
 						if *rpc.Payload.Value != "" {
 							return *rpc.Payload.Value
 						}
 					}
```
Comment (97gushan) [inline internal/kademlia/node.go:141]: no need to check payload value again

**Review by 97gushan — CHANGES_REQUESTED** [review]

**Review by 97gushan — APPROVED** [review]
